# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

# Use the latest Ubuntu VM image to run the pipeline

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
    sudo apt-get install -y nodejs
    node -v
    npm -v
  displayName: 'Install Node.js'

- script: |
    echo "Installing dependencies..."
    npm install
  displayName: 'Install dependencies'

- script: |
    echo "Building the app..."
    npm run build
  displayName: 'Build the app'
  env:
    NODE_OPTIONS: '--max_old_space_size=4096'

- script: |
    echo "Running tests..."
    npm test
  displayName: 'Run tests'
