# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

# Use the latest Ubuntu VM image to run the pipeline

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    versionSpec: '14.x'

- script: |
    echo "Node.js version:"
    node -v
    echo "NPM version:"
    npm -v
    echo "Installing dependencies..."
    npm install
  displayName: 'Install dependencies'
