# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

# Use the latest Ubuntu VM image to run the pipeline
pool:
  vmImage: 'ubuntu-latest'

# Define the steps to run in the pipeline
steps:
- task: UseNode@1
  inputs:
    versionSpec: '14.x'  # Specify the Node.js version you want to use

- script: npm install
  displayName: 'Install dependencies'

- script: npm run build
  displayName: 'Build the app'
  env:
    NODE_OPTIONS: '--max_old_space_size=4096'  # Optional: Increase memory limit

# Optionally, you can include a test step if you have tests
- script: npm test
  displayName: 'Run tests'
